---
title: "Shao"
author: "G.R. van der Ploeg"
date: "2024-03-12"
output: html_document
---

```{r setup}
library(parafac4microbiome)
library(tidyverse)
library(multiway)
library(ggpubr)
set.seed(123)
```

```{r prep plot data}
# Plot settings
colourCols = c("Delivery_mode", "phylum", "")
legendTitles = c("Delivery mode", "Phylum", "")
xLabels = c("Subject index", "Feature index", "Time index")
legendColNums = c(3,5,0)
arrangeModes = c(TRUE, TRUE, FALSE)
continuousModes = c(FALSE,FALSE,TRUE)
```

```{r check sparsity}
sparsity = calculateSparsity(Shao2019, considerGroups=TRUE, groupVariable="Delivery_mode") * 100

a=sparsity[1,] %>% as_tibble() %>% ggplot(aes(x=value)) + geom_histogram(col="black",bins=50) + xlab("Sparsity (%)") + ylab("Count") + ggtitle("C-section born") + geom_vline(xintercept=90, col="red", linewidth=1)
b=sparsity[2,] %>% as_tibble() %>% ggplot(aes(x=value)) + geom_histogram(col="black",bins=50) + xlab("Sparsity (%)") + ylab("Count") + ggtitle("Vaginally born") + geom_vline(xintercept=90, col="red", linewidth=1)
ggarrange(a,b)
```

```{r process the data}
processedShao = processDataCube(Shao2019, sparsityThreshold=0.9, considerGroups=TRUE, groupVariable="Delivery_mode", centerMode=1, scaleMode=2)
```

```{r investigate num comp}
# numRepetitions = 50
# qualityAssessment = assessModelQuality(processedShao$data, minNumComponents=1, maxNumComponents=5, numRepetitions=numRepetitions, ctol=1e-8, maxit=500, numCores=12)
```

```{r check the plots}
# qualityAssessment$plots$overview
```
```{r check why models converged}
# unlist(lapply(qualityAssessment$models[[1]], function(x){length(x$fs)}))
# unlist(lapply(qualityAssessment$models[[2]], function(x){length(x$fs)}))
# unlist(lapply(qualityAssessment$models[[3]], function(x){length(x$fs)}))
# unlist(lapply(qualityAssessment$models[[4]], function(x){length(x$fs)}))
# unlist(lapply(qualityAssessment$models[[5]], function(x){length(x$fs)}))
```

```{r model stability}
# numFolds = 50
# 
# stabilityAssessment = assessModelStability(processedShao, minNumComponents=1, maxNumComponents=3, numFolds=numFolds, colourCols=colourCols, legendTitles=legendTitles, xLabels=xLabels, legendColNums=legendColNums, arrangeModes=arrangeModes, numCores=4)
# 
# stabilityAssessment$modelPlots[[1]]
# stabilityAssessment$modelPlots[[2]]
# stabilityAssessment$modelPlots[[3]]
```

```{r select the model}
# numComponents = 3
# modelChoice = which(qualityAssessment$metrics$varExp[,numComponents] == max(qualityAssessment$metrics$varExp[,numComponents]))
# finalModel = qualityAssessment$models[[numComponents]][[modelChoice]]
# 
# saveRDS(finalModel, "./Shao2019_model.RDS")

finalModel = readRDS("./Shao2019_model.RDS")
```

```{r plot the model}
sampleMeta = read.csv("./Data/Shao_sampleMetadata.csv", skip=2) %>% as_tibble()

# Plot 3B - make by hand to deal with colour feedback

# Set up colours
colours = RColorBrewer:: brewer.pal(8, "Dark2")
bm_cols = colours[1:2]
phylum_cols = colours[-c(1:2)]

# Flip Fac where needed
Fac = finalModel$Fac
Fac[[2]][,2] = -1 * Fac[[2]][,2]
Fac[[1]][,2] = -1 * Fac[[1]][,2]

days = c("4", "7", "21", "Infancy")

a = cbind(Fac[[1]], processedShao$mode1) %>% as_tibble() %>% left_join(sampleMeta) %>% select(-Time_point,-Accession,-WGS_reads_raw,-WGS_reads_trimmed) %>% filter(Infancy_sampling_age_months != "Mother") %>% unique() %>% filter(!is.na(Abx_mother_labour_IAP)) %>% mutate(Abx = (Abx_mother_labour_IAP == "Yes")) %>% ggplot(aes(x=as.factor(Abx),y=`1`)) + geom_violin() + geom_jitter(width=0.02,height=0,size=0.75) + stat_compare_means(comparisons=list(c("TRUE","FALSE")),label="p.signif") + xlab("Antibiotics given to mother\n during labour") + ylab("Component 1") + scale_x_discrete(label=c("No", "Yes")) + theme(legend.position="none", text=element_text(size=12)) + ylim(-6,6)

b = cbind(Fac[[2]], processedShao$mode2) %>% as_tibble() %>% arrange(phylum, class, order, family, genus, mOTU, OTU) %>% mutate(index=1:nrow(.)) %>% ggplot(aes(x=index,y=`1`,fill=as.factor(phylum))) + geom_bar(stat="identity") + scale_fill_manual(name="Phylum", values=phylum_cols, labels=c("Actinobacteria", "Bacteroidetes", "Firmicutes", "Proteobacteria", "Unclassified")) + xlab("Feature index") + ylab("Component 1") + theme(legend.position="none", text=element_text(size=12)) 

c = Fac[[3]] %>% as_tibble() %>% mutate(index=1:nrow(.)) %>% ggplot(aes(x=index,y=V1)) + geom_line() + geom_point() + xlab("Time point [days]") + ylab("Component 1") + scale_x_discrete(name="Time point [days]",limits=days)

d = cbind(Fac[[1]], processedShao$mode1) %>% as_tibble() %>% left_join(sampleMeta) %>% select(-Time_point,-Accession,-WGS_reads_raw,-WGS_reads_trimmed) %>% filter(Infancy_sampling_age_months != "Mother") %>% unique() %>% filter(!is.na(Feeding_method)) %>% ggplot(aes(x=as.factor(Feeding_method),y=`2`)) + geom_violin() + geom_jitter(width=0.02,height=0,size=0.75) + stat_compare_means(comparisons=list(c("BF","NoBF")),label="p.signif") + xlab("Feeding method") + ylab("Component 2") + scale_x_discrete(label=c("Exclusively\n breastfed", "Mixed", "Not\n breastfed")) + theme(legend.position="none", text=element_text(size=12)) + ylim(-10,15)

e = cbind(Fac[[2]], processedShao$mode2) %>% as_tibble() %>% arrange(phylum, class, order, family, genus, mOTU, OTU) %>% mutate(index=1:nrow(.)) %>% ggplot(aes(x=index,y=`2`,fill=as.factor(phylum))) + geom_bar(stat="identity") + scale_fill_manual(name="Phylum", values=phylum_cols, labels=c("Actinobacteria", "Bacteroidetes", "Firmicutes", "Proteobacteria", "Unclassified")) + xlab("Feature index") + ylab("Component 2") + theme(legend.position="none", text=element_text(size=12)) 

f = Fac[[3]] %>% as_tibble() %>% mutate(index=1:nrow(.)) %>% ggplot(aes(x=index,y=V2)) + geom_line() + geom_point() + xlab("Time point [days]") + ylab("Component 2") + scale_x_discrete(name="Time point [days]",limits=days)

g = cbind(Fac[[1]], processedShao$mode1) %>% as_tibble() %>% left_join(sampleMeta) %>% select(-Time_point,-Accession,-WGS_reads_raw,-WGS_reads_trimmed) %>% filter(Infancy_sampling_age_months != "Mother") %>% unique() %>% ggplot(aes(x=as.factor(Delivery_mode),y=`3`)) + geom_violin() + geom_jitter(width=0.02,height=0,size=0.75) + stat_compare_means(comparisons=list(c("Caesarean","Vaginal")),label="p.signif") + xlab("Delivery mode") + ylab("Component 3") + theme(legend.position="none", text=element_text(size=12)) + ylim(-10,10)

h = cbind(Fac[[2]], processedShao$mode2) %>% as_tibble() %>% arrange(phylum, class, order, family, genus, mOTU, OTU) %>% mutate(index=1:nrow(.)) %>% ggplot(aes(x=index,y=`3`,fill=as.factor(phylum))) + geom_bar(stat="identity") + scale_fill_manual(name="Phylum", values=phylum_cols, labels=c("Actinobacteria", "Bacteroidetes", "Firmicutes", "Proteobacteria", "Unclassified")) + xlab("Feature index") + ylab("Component 3") + theme(legend.position="none", text=element_text(size=12)) 

i = Fac[[3]] %>% as_tibble() %>% mutate(index=1:nrow(.)) %>% ggplot(aes(x=index,y=V3)) + geom_line() + geom_point() + xlab("Time point [days]") + ylab("Component 3") + scale_x_discrete(name="Time point [days]",limits=days)

ggarrange(a,b,c,d,e,f,g,h,i)
```

```{r loading plot}
threshold=0.00
# threshold = 0.070

temp1 = cbind(Fac[[2]], processedShao$mode2) %>% as_tibble() %>% arrange(`1`) %>% mutate(index=1:nrow(.)) %>% filter(abs(`1`) > threshold)
name = str_split_fixed(temp1$mOTU, " \\[", 2)[,1]
name = str_split_fixed(name, " ", 3)[,2:3] %>% as_tibble()
name[name$V1 == "","V1"] = "Unclassified"
name = paste0(name$V1, " ", name$V2)

a = temp1 %>% ggplot(aes(x=`1`,y=as.factor(index),fill=as.factor(phylum))) + geom_bar(stat="identity") + ylab("Microbiota") + xlab("Component 1") + scale_y_discrete(labels=name) + scale_fill_manual(name="Phylum", values=phylum_cols, labels=c("Actinobacteria", "Bacteroidetes", "Firmicutes", "Proteobacteria", "Unclassified")) + ylab("") + theme(legend.position="none", text=element_text(size=16))

temp2 = cbind(Fac[[2]], processedShao$mode2) %>% as_tibble() %>% arrange(`2`) %>% mutate(index=1:nrow(.)) %>% filter(abs(`2`) > threshold)
name = str_split_fixed(temp2$mOTU, " \\[", 2)[,1]
name = str_split_fixed(name, " ", 3)[,2:3] %>% as_tibble()
name[name$V1 == "","V1"] = "Unclassified"
name = paste0(name$V1, " ", name$V2)

b = temp2 %>% ggplot(aes(x=`2`,y=as.factor(index),fill=as.factor(phylum))) + geom_bar(stat="identity") + ylab("Microbiota") + xlab("Component 2") + scale_y_discrete(labels=name) + scale_fill_manual(name="Phylum", values=phylum_cols, labels=c("Actinobacteria", "Bacteroidetes", "Firmicutes", "Proteobacteria", "Unclassified"))+ ylab("") + theme(legend.position="none", text=element_text(size=16)) 

temp3 = cbind(Fac[[2]], processedShao$mode2) %>% as_tibble() %>% arrange(`3`) %>% mutate(index=1:nrow(.)) %>% filter(abs(`3`) > threshold)
name = str_split_fixed(temp3$mOTU, " \\[", 2)[,1]
name = str_split_fixed(name, " ", 3)[,2:3] %>% as_tibble()
name[name$V1 == "","V1"] = "Unclassified"
name = paste0(name$V1, " ", name$V2)

c = temp3 %>% ggplot(aes(x=`3`,y=as.factor(index),fill=as.factor(phylum))) + geom_bar(stat="identity") + ylab("Microbiota") + xlab("Component 3") + scale_y_discrete(labels=name) + scale_fill_manual(name="Phylum", values=phylum_cols, labels=c("Actinobacteria", "Bacteroidetes", "Firmicutes", "Proteobacteria", "Unclassified")) + ylab("") + theme(legend.position="none", text=element_text(size=16)) 
ggarrange(a,b,c, nrow=1)
```

```{r create relabs plot}
I = dim(Shao2019$data)[1]
J = dim(Shao2019$data)[2]
K = dim(Shao2019$data)[3]
timepoints = c("4", "7", "21", "Infancy")

countMatrix = matrix(Shao2019$data, nrow=I)
newColNames = paste0(rep(Shao2019$mode2$OTU,K), "_t", rep(1:K, each=J))
colnames(countMatrix) = newColNames
countMatrix = countMatrix %>% as_tibble() %>% mutate(subject=Shao2019$mode1$Individual) %>% pivot_longer(-subject) %>% mutate(timepoint=as.numeric(str_split_fixed(name,"_t",2)[,2]),id=str_split_fixed(name,"_t",2)[,1]) %>% select(-name) %>% pivot_wider(names_from=id,values_from=value) # shenanigans to create an I*K x J matrix
countMatrix.numeric = countMatrix %>% select(processedShao$mode2$OTU)

totalSums = rowSums(countMatrix.numeric)
relAbs = sweep(countMatrix.numeric, 1, totalSums, FUN="/") %>% as_tibble()

# Plot 3A
relAbs %>% mutate(subject=countMatrix$subject, timepoint=timepoints[countMatrix$timepoint]) %>% pivot_longer(-c(subject,timepoint)) %>% filter(name %in% processedShao$mode2$OTU) %>% left_join(Shao2019$mode1, by=c("subject"="Individual")) %>% left_join(Shao2019$mode2, by=c("name"="OTU")) %>% group_by(subject,timepoint,phylum) %>% summarize(s=sum(value)) %>% left_join(Shao2019$mode1, by=c("subject"="Individual")) %>% ungroup() %>% group_by(Delivery_mode,phylum,timepoint) %>% summarize(m=mean(s,na.rm=TRUE)) %>% ungroup() %>% mutate(timepoint = factor(timepoint, levels=c("4","7","21","Infancy"))) %>% ggplot(aes(x=as.factor(timepoint),y=m,fill=as.factor(phylum))) + facet_wrap(vars(Delivery_mode),nrow=2,strip.position="right") + geom_bar(stat="identity") + xlab("Time point [days]") + ylab("Relative abundance") + scale_fill_manual(name="Phylum", values=phylum_cols, labels=c("Actinobacteria", "Bacteroidetes", "Firmicutes", "Proteobacteria", "Unclassified")) + theme(legend.position="none", text=element_text(size=14))

relAbs %>% mutate(subject=countMatrix$subject, timepoint=countMatrix$timepoint) %>% pivot_longer(-c(subject,timepoint)) %>% filter(name %in% processedShao$mode2$OTU) %>% left_join(Shao2019$mode1, by=c("subject"="Individual")) %>% left_join(Shao2019$mode2, by=c("name"="OTU")) %>% group_by(subject,timepoint,phylum) %>% summarize(s=sum(value)) %>% left_join(Shao2019$mode1, by=c("subject"="Individual")) %>% ungroup() %>% group_by(Delivery_mode,phylum,timepoint) %>% summarize(m=mean(s,na.rm=TRUE)) %>% ungroup() %>% ggplot(aes(x=as.factor(timepoint),y=m,fill=as.factor(phylum))) + facet_wrap(vars(Delivery_mode),nrow=2,strip.position="right") + geom_bar(stat="identity") + xlab("Time point [days]") + ylab("Relative abundance") + scale_fill_manual(name="Phylum", values=phylum_cols, labels=c("Actinobacteria", "Bacteroidetes", "Firmicutes", "Proteobacteria", "Unclassified"))
```

```{r test metadata}
sampleMeta = read.csv("./Data/Shao_sampleMetadata.csv", skip=2) %>% as_tibble()
subjectLoadings = cbind(Fac[[1]], processedShao$mode1) %>% as_tibble() %>% left_join(sampleMeta) %>% select(-Time_point,-Accession,-WGS_reads_raw,-WGS_reads_trimmed) %>% filter(Infancy_sampling_age_months != "Mother") %>% unique()

transformedSubjectLoadings = transformPARAFACloadings(Fac, 2, moreOutput=TRUE)$Ftilde %>% as_tibble() %>% mutate(Individual = rep(processedShao$mode1$Individual, each=4), Time_point = rep(c(4,7,21,"Infancy"),1580/4)) %>% left_join(sampleMeta)

uncorrectedP = matrix(0L, nrow=3, ncol=7)

# Delivery mode
uncorrectedP[1,1] = wilcox.test(subjectLoadings %>% filter(Delivery_mode == "Caesarean") %>% select(`1`) %>% pull(),
                                subjectLoadings %>% filter(Delivery_mode == "Vaginal") %>% select(`1`) %>% pull())$p.value
uncorrectedP[2,1] = wilcox.test(subjectLoadings %>% filter(Delivery_mode == "Caesarean") %>% select(`2`) %>% pull(),
                                subjectLoadings %>% filter(Delivery_mode == "Vaginal") %>% select(`2`) %>% pull())$p.value
uncorrectedP[3,1] = wilcox.test(subjectLoadings %>% filter(Delivery_mode == "Caesarean") %>% select(`3`) %>% pull(),
                                subjectLoadings %>% filter(Delivery_mode == "Vaginal") %>% select(`3`) %>% pull())$p.value

# Feeding method
uncorrectedP[1,2] = wilcox.test(subjectLoadings %>% filter(Feeding_method == "BF") %>% select(`1`) %>% pull(),
                                subjectLoadings %>% filter(Feeding_method == "NoBF") %>% select(`1`) %>% pull())$p.value
uncorrectedP[2,2] = wilcox.test(subjectLoadings %>% filter(Feeding_method == "BF") %>% select(`2`) %>% pull(),
                                subjectLoadings %>% filter(Feeding_method == "NoBF") %>% select(`2`) %>% pull())$p.value
uncorrectedP[3,2] = wilcox.test(subjectLoadings %>% filter(Feeding_method == "BF") %>% select(`3`) %>% pull(),
                                subjectLoadings %>% filter(Feeding_method == "NoBF") %>% select(`3`) %>% pull())$p.value

# Gender
uncorrectedP[1,3] = wilcox.test(subjectLoadings %>% filter(Gender == "Male") %>% select(`1`) %>% pull(),
                                subjectLoadings %>% filter(Gender == "Female") %>% select(`1`) %>% pull())$p.value
uncorrectedP[2,3] = wilcox.test(subjectLoadings %>% filter(Gender == "Male") %>% select(`2`) %>% pull(),
                                subjectLoadings %>% filter(Gender == "Female") %>% select(`2`) %>% pull())$p.value
uncorrectedP[3,3] = wilcox.test(subjectLoadings %>% filter(Gender == "Male") %>% select(`3`) %>% pull(),
                                subjectLoadings %>% filter(Gender == "Female") %>% select(`3`) %>% pull())$p.value

# Abx mother during labour
uncorrectedP[1,4] = wilcox.test(subjectLoadings %>% filter(Abx_mother_labour_IAP == "Yes") %>% select(`1`) %>% pull(),
                                subjectLoadings %>% filter(Abx_mother_labour_IAP != "Yes") %>% select(`1`) %>% pull())$p.value
uncorrectedP[2,4] = wilcox.test(subjectLoadings %>% filter(Abx_mother_labour_IAP == "Yes") %>% select(`2`) %>% pull(),
                                subjectLoadings %>% filter(Abx_mother_labour_IAP != "Yes") %>% select(`2`) %>% pull())$p.value
uncorrectedP[3,4] = wilcox.test(subjectLoadings %>% filter(Abx_mother_labour_IAP == "Yes") %>% select(`3`) %>% pull(),
                                subjectLoadings %>% filter(Abx_mother_labour_IAP != "Yes") %>% select(`3`) %>% pull())$p.value

# Abx baby in hospital
uncorrectedP[1,5] = wilcox.test(subjectLoadings %>% filter(Abx_Baby_in_hospital  == "Yes") %>% select(`1`) %>% pull(),
                                subjectLoadings %>% filter(Abx_Baby_in_hospital  != "Yes") %>% select(`1`) %>% pull())$p.value
uncorrectedP[2,5] = wilcox.test(subjectLoadings %>% filter(Abx_Baby_in_hospital  == "Yes") %>% select(`2`) %>% pull(),
                                subjectLoadings %>% filter(Abx_Baby_in_hospital  != "Yes") %>% select(`2`) %>% pull())$p.value
uncorrectedP[3,5] = wilcox.test(subjectLoadings %>% filter(Abx_Baby_in_hospital  == "Yes") %>% select(`3`) %>% pull(),
                                subjectLoadings %>% filter(Abx_Baby_in_hospital  != "Yes") %>% select(`3`) %>% pull())$p.value

# Abx baby after hospital
uncorrectedP[1,6] = wilcox.test(subjectLoadings %>% filter(Abx_Baby_after_hospital  == "Yes") %>% select(`1`) %>% pull(),
                                subjectLoadings %>% filter(Abx_Baby_after_hospital  == "No") %>% select(`1`) %>% pull())$p.value
uncorrectedP[2,6] = wilcox.test(subjectLoadings %>% filter(Abx_Baby_after_hospital  == "Yes") %>% select(`2`) %>% pull(),
                                subjectLoadings %>% filter(Abx_Baby_after_hospital  == "No") %>% select(`2`) %>% pull())$p.value
uncorrectedP[3,6] = wilcox.test(subjectLoadings %>% filter(Abx_Baby_after_hospital  == "Yes") %>% select(`3`) %>% pull(),
                                subjectLoadings %>% filter(Abx_Baby_after_hospital  == "No") %>% select(`3`) %>% pull())$p.value

# Bacteroides profile
uncorrectedP[1,7] = wilcox.test(subjectLoadings %>% filter(Bacteroides_profile  == "low_Bacteroides") %>% select(`1`) %>% pull(),
                                subjectLoadings %>% filter(Bacteroides_profile  == "normal_Bacteroides") %>% select(`1`) %>% pull())$p.value
uncorrectedP[2,7] = wilcox.test(subjectLoadings %>% filter(Bacteroides_profile  == "low_Bacteroides") %>% select(`2`) %>% pull(),
                                subjectLoadings %>% filter(Bacteroides_profile  == "normal_Bacteroides") %>% select(`2`) %>% pull())$p.value
uncorrectedP[3,7] = wilcox.test(subjectLoadings %>% filter(Bacteroides_profile  == "low_Bacteroides") %>% select(`3`) %>% pull(),
                                subjectLoadings %>% filter(Bacteroides_profile  == "normal_Bacteroides") %>% select(`3`) %>% pull())$p.value

correctedP = matrix(p.adjust(uncorrectedP, "BH"), nrow=3, ncol=7)
correctedP
```