---
title: "modelInterpretation"
author: "G.R. van der Ploeg"
date: "11/30/2023"
output: html_document
---

```{r libraries}
library(ggplot2)
library(tidyverse)
library(ggrepel)
library(ggpubr)
library(paramGUI)
library(pracma)
library(plotly)

source("../../N-way-shell-R/summary.functions.R")
source("../../N-way-shell-R/PARAFAC_functions.R")
source("../../N-way-shell-R/heatmap.2a.R")
source("../../N-way-shell-R/plotfunctions.R")
set.seed(0)
```
```{r import model}
path = "./20231130_run/PARAFAC models/Shao"
mode1ColNames = c("subject", "birth_mode")
mode2ColNames = c("num1", "num2", "motus", "num3")
mode3ColNames = c("month")
subjectIDs = "subject"
featureIDs = "motus"
numComponents = 3

model = importPARAFAC(path, mode1ColNames, mode2ColNames, mode3ColNames, subjectIDs, featureIDs, numComponents)
```

```{r import taxonomy}
taxonomy = read.csv("./Data/db_mOTU_taxonomy_ref-mOTUs.tsv", sep="\t") %>% as_tibble()
taxonomy$kingdom = str_split_fixed(taxonomy$kingdom, " ", 2)[,2]
taxonomy$phylum = str_split_fixed(taxonomy$phylum, " ", 2)[,2]
taxonomy$class = str_split_fixed(taxonomy$class, " ", 2)[,2]
taxonomy$order = str_split_fixed(taxonomy$order, " ", 2)[,2]
taxonomy$family = str_split_fixed(taxonomy$family, " ", 2)[,2]
taxonomy$genus = str_split_fixed(taxonomy$genus, " ", 2)[,2]

fixedIDs = str_sub(model[[2]]$motus, -20, -2)
fixedIDs = gsub("\\[", "", fixedIDs)

model[[2]] = model[[2]] %>% select(-num1,-num2,-num3) %>% mutate(motusID = fixedIDs) %>% left_join(taxonomy, by=c("motusID"="ref.mOTU_v2_ID"))
# model[[2]]$kingdom = str_split_fixed(model[[2]]$kingdom, " ", 2)[,2]
# model[[2]]$phylum = str_split_fixed(model[[2]]$phylum, " ", 2)[,2]
# model[[2]]$class = str_split_fixed(model[[2]]$class, " ", 2)[,2]
# model[[2]]$order = str_split_fixed(model[[2]]$order, " ", 2)[,2]
# model[[2]]$family = str_split_fixed(model[[2]]$family, " ", 2)[,2]
# model[[2]]$genus = str_split_fixed(model[[2]]$genus, " ", 2)[,2]
```

```{r model plot}
mask = !is.na(model[[7]])
varExp = round(sum(model[[6]][mask]^2, na.rm=TRUE) / sum(model[[7]][mask]^2, na.rm=TRUE) * 100, 2)

colourCols = c("birth_mode", "phylum", "")
legendTitles = c("Birth mode","Phylum","Day")
xLabels = c("Subject index","Feature index","Time index")
legendColNums = c(2,3,3)
arrangeModes = c(TRUE,TRUE,FALSE)
continuousModes = c(FALSE,FALSE,TRUE)
overallTitle = "Shao PARAFAC (14.87% variance explained)"

plotPARAFACModel(model, colourCols, legendTitles, xLabels, legendColNums, arrangeModes, continuousModes, overallTitle)
```

```{r prep data for paper figure}
countData = read.csv("./Data/count-table_clean.csv", sep=" ", header=FALSE) %>% as_tibble()
taxa = read.csv("./Data/speciesMetadata_clean.csv", sep=" ", header=FALSE) %>% as_tibble()
sampleMetadata = read.csv("./Data/sampleMetadata_clean.csv", sep=" ", header=FALSE) %>% as_tibble()

# Fixing col names
sp = str_split_fixed(taxa$V3, " ", 7)
colSelection = rowSums(sp != "")
fixedNames = 1:nrow(sp)
for(i in 1:nrow(sp)){
  fixedNames[i] = sp[i,colSelection[i]]
}
fixedNames = gsub("\\[", "", fixedNames)
fixedNames = gsub("\\]", "", fixedNames)

colnames(countData) = fixedNames
colnames(sampleMetadata) = c("accession", "subject", "timepoint", "birth_mode", "c_section_type", "infancy_sampling", "postnatal_stay_days", "hospital", "hospital_destination", "gender", "mother_age", "birth_weight", "feeding_method", "breastfeeding_status", "breastfeeding_1h_after_birth", "abx_mother_prior_birth", "abx_mother_labour", "abx_mother_after", "abx_baby_in_hospital", "abx_baby_after_hospital", "bacteroides_profile", "WGS_reads_raw", "WGS_reads_trimmed", "study_accession", "secondary_study_accession", "sample_accession", "secondary_sample_accession", "experiment_Accession", "run_accession", "tax_id", "scientific_name", "fastq_ftp", "submitted_ftp", "sra_ftp", "bam_ftp")
colnames(taxa) = c("bla1", "bla2", "name", "bla3")

relAbs = sweep(countData, 1, rowSums(countData), FUN="/")

```

```{r try some plots}
selection = model[[2]] %>% select(genus) %>% pull() %>% unique()
asvSelection = taxonomy %>% filter(genus %in% selection) %>% select(ref.mOTU_v2_ID) %>% pull()

# Overview plot of vaginal vs caesarean
df1 = rbind(countData %>% mutate(subject = sampleMetadata$subject, timepoint = sampleMetadata$timepoint, birth_mode = sampleMetadata$birth_mode) %>% filter(birth_mode == "Vaginal", timepoint == 4) %>% select(-subject,-timepoint,-birth_mode) %>% colMeans(),
           countData %>% mutate(subject = sampleMetadata$subject, timepoint = sampleMetadata$timepoint, birth_mode = sampleMetadata$birth_mode) %>% filter(birth_mode == "Vaginal", timepoint == 7) %>% select(-subject,-timepoint,-birth_mode) %>% colMeans(),
           countData %>% mutate(subject = sampleMetadata$subject, timepoint = sampleMetadata$timepoint, birth_mode = sampleMetadata$birth_mode) %>% filter(birth_mode == "Vaginal", timepoint == 21) %>% select(-subject,-timepoint,-birth_mode) %>% colMeans(),
           countData %>% mutate(subject = sampleMetadata$subject, timepoint = sampleMetadata$timepoint, birth_mode = sampleMetadata$birth_mode) %>% filter(birth_mode == "Vaginal", timepoint == "Infancy") %>% select(-subject,-timepoint,-birth_mode) %>% colMeans())
df1 = sweep(df1, 1, rowSums(df1), FUN="/")
df1 = df1 %>% as_tibble() %>% mutate(timepoint = c(4,7,21,"Infancy")) %>% mutate(timepoint = factor(timepoint, levels=c(4,7,21,"Infancy"))) %>% pivot_longer(-timepoint) %>% left_join(taxonomy, by=c("name"="ref.mOTU_v2_ID")) %>% mutate(birth_mode = "Vaginal")

#  ------------------
df2 = rbind(countData %>% mutate(subject = sampleMetadata$subject, timepoint = sampleMetadata$timepoint, birth_mode = sampleMetadata$birth_mode) %>% filter(birth_mode == "Caesarean", timepoint == 4) %>% select(-subject,-timepoint,-birth_mode) %>% colMeans(),
           countData %>% mutate(subject = sampleMetadata$subject, timepoint = sampleMetadata$timepoint, birth_mode = sampleMetadata$birth_mode) %>% filter(birth_mode == "Caesarean", timepoint == 7) %>% select(-subject,-timepoint,-birth_mode) %>% colMeans(),
           countData %>% mutate(subject = sampleMetadata$subject, timepoint = sampleMetadata$timepoint, birth_mode = sampleMetadata$birth_mode) %>% filter(birth_mode == "Caesarean", timepoint == 21) %>% select(-subject,-timepoint,-birth_mode) %>% colMeans(),
           countData %>% mutate(subject = sampleMetadata$subject, timepoint = sampleMetadata$timepoint, birth_mode = sampleMetadata$birth_mode) %>% filter(birth_mode == "Caesarean", timepoint == "Infancy") %>% select(-subject,-timepoint,-birth_mode) %>% colMeans())
df2 = sweep(df2, 1, rowSums(df2), FUN="/")
df2 = df2 %>% as_tibble() %>% mutate(timepoint = c(4,7,21,"Infancy")) %>% mutate(timepoint = factor(timepoint, levels=c(4,7,21,"Infancy"))) %>% pivot_longer(-timepoint) %>% left_join(taxonomy, by=c("name"="ref.mOTU_v2_ID")) %>% mutate(birth_mode = "Caesarean")

df = rbind(df1,df2) %>% as_tibble()
df %>% filter(phylum %in% model[[2]]$phylum) %>% ggplot(aes(x=as.factor(timepoint),y=value,fill=as.factor(phylum))) + facet_grid(vars(birth_mode)) + geom_bar(stat="identity") + theme(legend.position = "none", text=element_text(size=14)) + ylab("Relative abundance") + xlab("Time point [days]") + scale_fill_manual(name="Phylum", labels=c("Actinobacteria", "Bacteroidetes", "Firmicutes", "Proteobacteria", "Unclassified"), values=c("#DB72FB", "#93AA00", "#00B9E3", "#FF61C3"))
```

```{r try more plots}
countData2 = countData
colnames(countData2) = taxa$name

selection = model[[2]] %>% filter(Component_1 > 0) %>% select(motus) %>% pull()
countData2 %>% mutate(subject = sampleMetadata$subject, timepoint = sampleMetadata$timepoint) %>% pivot_longer(-c(subject,timepoint)) %>% filter(name %in% selection) %>% group_by(subject,timepoint) %>% summarize(s=log10(sum(value)+1)) %>% ungroup() %>% left_join(sampleMetadata) %>% filter(feeding_method %in% c("BF", "NoBF")) %>% mutate(feeding_method = as.factor(feeding_method)) %>% group_by(feeding_method, timepoint) %>% summarize(m=mean(s, na.rm=TRUE),v=plotrix::std.error(s, na.rm=TRUE)) %>% ungroup() %>% mutate(feeding_method = as.factor(feeding_method)) %>% filter(timepoint %in% c(4,7,21)) %>% mutate(timepoint = factor(timepoint, levels=c(4,7,21))) %>% ggplot(aes(x=timepoint,y=m,group=feeding_method,col=feeding_method)) + geom_line() + geom_point() + geom_errorbar(aes(ymax=m+v,ymin=m-v),width=.2) + xlab("Time point") + ylab("Sum of ASVs per group (mean +/- SEM")

selection = model[[2]] %>% filter(Component_2 > 0) %>% select(motus) %>% pull()

countData2 %>% mutate(subject = sampleMetadata$subject, timepoint = sampleMetadata$timepoint) %>% pivot_longer(-c(subject,timepoint)) %>% filter(name %in% selection) %>% group_by(subject,timepoint) %>% summarize(s=log10(sum(value)+1)) %>% ungroup() %>% group_by(timepoint) %>% summarize(m=mean(s,na.rm=TRUE),v=plotrix::std.error(s,na.rm=TRUE)) %>% filter(timepoint %in% c(4,7,21,"Infancy")) %>% mutate(timepoint = factor(timepoint, level=c(4,7,21,"Infancy"))) %>% ggplot(aes(x=timepoint,y=m)) + geom_point()

selection = model[[2]] %>% filter(Component_3 > 0) %>% select(motus) %>% pull()

countData2 %>% mutate(subject = sampleMetadata$subject, timepoint = sampleMetadata$timepoint, birth_mode = sampleMetadata$birth_mode) %>% pivot_longer(-c(subject,timepoint,birth_mode)) %>% filter(name %in% selection) %>% group_by(subject,birth_mode,timepoint) %>% summarize(s=log10(sum(value)+1)) %>% ungroup() %>% mutate(birth_mode = as.factor(birth_mode)) %>% group_by(birth_mode, timepoint) %>% summarize(m=mean(s, na.rm=TRUE),v=plotrix::std.error(s, na.rm=TRUE)) %>% ungroup() %>% mutate(birth_mode = as.factor(birth_mode)) %>% filter(timepoint %in% c(4,7,21,"Infancy")) %>% mutate(timepoint = factor(timepoint, levels=c(4,7,21,"Infancy"))) %>% ggplot(aes(x=timepoint,y=m,group=birth_mode,col=birth_mode)) + geom_line() + geom_point() + geom_errorbar(aes(ymax=m+v,ymin=m-v),width=.2) + xlab("Time point") + ylab("Sum of ASVs per group (mean +/- SEM") + theme(text=element_text(size=16))

countData2 %>% mutate(subject = sampleMetadata$subject, timepoint = sampleMetadata$timepoint, birth_mode = sampleMetadata$birth_mode) %>% pivot_longer(-c(subject,timepoint,birth_mode)) %>% filter(name %in% selection) %>% group_by(subject,birth_mode,timepoint) %>% summarize(s=sum(value)+1) %>% ungroup() %>% mutate(birth_mode = as.factor(birth_mode)) %>% filter(timepoint %in% c(4,7,21,"Infancy")) %>% ggplot(aes(x=as.factor(birth_mode),y=s)) + facet_grid(vars(timepoint)) + geom_boxplot() + stat_compare_means()
```

```{r paper figure}
#a = model[[1]] %>% left_join(sampleMetadata) %>% arrange(feeding_method) %>% mutate(index=1:nrow(.)) %>% ggplot(aes(x=index,y=Component_1,fill=as.factor(feeding_method))) + geom_bar(stat="identity") + scale_fill_manual(name="Feeding method", labels=c("Exclusively breastfed", "Mixed", "Exclusively formula", "Unknown"), values=c("#F8766D", "#00BA38", "#619CFF", "gray")) + xlab("") + ylab("Component 1")
#show_col(hue_pal()(9))

a = model[[1]] %>% left_join(sampleMetadata) %>% arrange(feeding_method) %>% mutate(index=1:nrow(.)) %>% ggplot(aes(x=index,y=Component_1,fill=as.factor(feeding_method))) + geom_bar(stat="identity") + theme(legend.position="none") + xlab("") + ylab("Component 1") + theme(text=element_text(size=14)) + scale_fill_manual(name="Feeding method", labels=c("Exclusive breastfeeding","Mixed feeding","Exclusive formula feeding","Unknown"), values=c("#F8766D", "#00BA38", "#619CFF", "gray"))

b = model[[2]] %>% arrange(phylum) %>% mutate(index=1:nrow(.)) %>% ggplot(aes(x=index,y=Component_1,fill=phylum)) + geom_bar(stat="identity") + xlab("") + ylab("") + theme(legend.position="none") + theme(text=element_text(size=14)) + scale_fill_manual(name="Phylum", labels=c("Actinobacteria", "Bacteroidetes", "Firmicutes", "Proteobacteria", "Unclassified"), values=c("#DB72FB", "#93AA00", "#00B9E3", "#FF61C3"))
c = model[[3]] %>% ggplot(aes(x=month,y=Component_1)) + geom_line() + xlab("") + ylab("") + theme(text=element_text(size=14))

d = model[[1]] %>% mutate(index=1:nrow(.)) %>% ggplot(aes(x=index,y=Component_2)) + geom_bar(stat="identity") + xlab("") + ylab("Component 2") + theme(text=element_text(size=14))
e = model[[2]] %>% arrange(phylum) %>% mutate(index=1:nrow(.)) %>% ggplot(aes(x=index,y=Component_2,fill=phylum)) + geom_bar(stat="identity") + xlab("") + ylab("") + theme(legend.position="none") + theme(text=element_text(size=14)) + scale_fill_manual(name="Phylum", labels=c("Actinobacteria", "Bacteroidetes", "Firmicutes", "Proteobacteria", "Unclassified"), values=c("#DB72FB", "#93AA00", "#00B9E3", "#FF61C3"))
f = model[[3]] %>% ggplot(aes(x=month,y=Component_2)) + geom_line() + xlab("") + ylab("") + theme(text=element_text(size=14))

g = model[[1]] %>% arrange(birth_mode) %>% mutate(index=1:nrow(.)) %>% ggplot(aes(x=index,y=Component_3,fill=as.factor(birth_mode))) + geom_bar(stat="identity") + theme(legend.position="none") + xlab("Subject index") + ylab("Component 3") + theme(text=element_text(size=14)) + scale_fill_manual(name="Birth mode", labels=c("Caesarean", "Vaginal"), values = c("#D39200", "#00C19F"))
h = model[[2]] %>% arrange(phylum) %>% mutate(index=1:nrow(.)) %>% ggplot(aes(x=index,y=Component_3,fill=phylum)) + geom_bar(stat="identity") + xlab("Feature index") + ylab("") + theme(legend.position="none") + theme(text=element_text(size=14)) + scale_fill_manual(name="Phylum", labels=c("Actinobacteria", "Bacteroidetes", "Firmicutes", "Proteobacteria", "Unclassified"), values=c("#DB72FB", "#93AA00", "#00B9E3", "#FF61C3"))
i = model[[3]] %>% ggplot(aes(x=month,y=Component_3)) + geom_line() + xlab("Time point [days]") + ylab("") + theme(text=element_text(size=14))
ggarrange(a,b,c,d,e,f,g,h,i,nrow=3,ncol=3)

model[[1]] %>% left_join(sampleMetadata) %>% arrange(feeding_method) %>% mutate(index=1:nrow(.)) %>% ggplot(aes(x=index,y=Component_1,fill=as.factor(feeding_method))) + geom_bar(stat="identity") + theme(legend.position="bottom") + xlab("") + ylab("Component 1") + theme(text=element_text(size=14)) + scale_fill_manual(name="Feeding method", labels=c("Exclusive breastfeeding","Mixed feeding","Exclusive formula feeding","Unknown"), values=c("#F8766D", "#00BA38", "#619CFF", "gray")) + guides(fill=guide_legend(ncol=1))

model[[1]] %>% arrange(birth_mode) %>% mutate(index=1:nrow(.)) %>% ggplot(aes(x=index,y=Component_3,fill=as.factor(birth_mode))) + geom_bar(stat="identity") + theme(legend.position="bottom") + xlab("Subject index") + ylab("Component 3") + theme(text=element_text(size=14)) + scale_fill_manual(name="Birth mode", labels=c("Caesarean", "Vaginal"), values = c("#D39200", "#00C19F")) + guides(fill=guide_legend(ncol=1))

model[[2]] %>% arrange(phylum) %>% mutate(index=1:nrow(.)) %>% ggplot(aes(x=index,y=Component_1,fill=phylum)) + geom_bar(stat="identity") + xlab("") + ylab("") + theme(legend.position="bottom") + theme(text=element_text(size=14)) + scale_fill_manual(name="Phylum", labels=c("Actinobacteria", "Bacteroidetes", "Firmicutes", "Proteobacteria", "Unclassified"), values=c("#DB72FB", "#93AA00", "#00B9E3", "#FF61C3")) + guides(fill=guide_legend(ncol=1))


# --------------------------------
selection = model[[2]] %>% filter(Component_3 > 0) %>% select(motus) %>% pull()

countData2 %>% mutate(subject = sampleMetadata$subject, timepoint = sampleMetadata$timepoint, birth_mode = sampleMetadata$birth_mode) %>% pivot_longer(-c(subject,timepoint,birth_mode)) %>% filter(name %in% selection) %>% group_by(subject,birth_mode,timepoint) %>% summarize(s=log10(sum(value)+1)) %>% ungroup() %>% mutate(birth_mode = as.factor(birth_mode)) %>% group_by(birth_mode, timepoint) %>% summarize(m=mean(s, na.rm=TRUE),v=plotrix::std.error(s, na.rm=TRUE)) %>% ungroup() %>% mutate(birth_mode = as.factor(birth_mode)) %>% filter(timepoint %in% c(4,7,21,"Infancy")) %>% mutate(timepoint = factor(timepoint, levels=c(4,7,21,"Infancy"))) %>% ggplot(aes(x=timepoint,y=m,group=birth_mode,col=birth_mode)) + geom_line() + geom_point() + geom_errorbar(aes(ymax=m+v,ymin=m-v),width=.2) + xlab("Time point") + ylab("Sum of ASVs per group (mean +/- SEM)") + scale_color_discrete(name="Birth mode") + theme(text=element_text(size=14), legend.position="top")
```

```{r test loadings against subject metadata more formally}


testVariables = c("birth_mode", "hospital", "gender", "feeding_method", "abx_mother_labour", "abx_baby_in_hospital", "abx_baby_after_hospital", "bacteroides_profile")

results = c()

# Birth mode
results = c(results, wilcox.test(model[[1]] %>% filter(birth_mode == "Vaginal") %>% select(Component_1) %>% pull(), 
                          model[[1]] %>% filter(birth_mode == "Caesarean") %>% select(Component_1) %>% pull())$p.value)
results = c(results, wilcox.test(model[[1]] %>% filter(birth_mode == "Vaginal") %>% select(Component_2) %>% pull(), 
                          model[[1]] %>% filter(birth_mode == "Caesarean") %>% select(Component_2) %>% pull())$p.value)
results = c(results, wilcox.test(model[[1]] %>% filter(birth_mode == "Vaginal") %>% select(Component_3) %>% pull(), 
                          model[[1]] %>% filter(birth_mode == "Caesarean") %>% select(Component_3) %>% pull())$p.value)

# Hospital
temp = model[[1]] %>% left_join(sampleMetadata %>% select(subject, hospital) %>% unique())
results = c(results, kruskal.test(temp$Component_1, temp$hospital)$p.value)
results = c(results, kruskal.test(temp$Component_2, temp$hospital)$p.value)
results = c(results, kruskal.test(temp$Component_3, temp$hospital)$p.value)

# Feeding method
temp = model[[1]] %>% left_join(sampleMetadata %>% select(subject, feeding_method) %>% unique())
results = c(results, wilcox.test(temp %>% filter(feeding_method == "BF") %>% select(Component_1) %>% pull(),
                                 temp %>% filter(feeding_method == "NoBF") %>% select(Component_1) %>% pull())$p.value)
results = c(results, wilcox.test(temp %>% filter(feeding_method == "BF") %>% select(Component_2) %>% pull(),
                                 temp %>% filter(feeding_method == "NoBF") %>% select(Component_2) %>% pull())$p.value)
results = c(results, wilcox.test(temp %>% filter(feeding_method == "BF") %>% select(Component_3) %>% pull(),
                                 temp %>% filter(feeding_method == "NoBF") %>% select(Component_3) %>% pull())$p.value)

# Antibiotics for mother in hospital
temp = model[[1]] %>% left_join(sampleMetadata %>% select(subject, abx_mother_labour) %>% unique())
results = c(results, wilcox.test(temp %>% filter(abx_mother_labour == "No") %>% select(Component_1) %>% pull(),
                                 temp %>% filter(abx_mother_labour == "Yes") %>% select(Component_1) %>% pull())$p.value)
results = c(results, wilcox.test(temp %>% filter(abx_mother_labour == "No") %>% select(Component_2) %>% pull(),
                                 temp %>% filter(abx_mother_labour == "Yes") %>% select(Component_2) %>% pull())$p.value)
results = c(results, wilcox.test(temp %>% filter(abx_mother_labour == "No") %>% select(Component_3) %>% pull(),
                                 temp %>% filter(abx_mother_labour == "Yes") %>% select(Component_3) %>% pull())$p.value)

# Antibiotics for baby in hospital
temp = model[[1]] %>% left_join(sampleMetadata %>% select(subject, abx_baby_in_hospital) %>% unique())
results = c(results, wilcox.test(temp %>% filter(abx_baby_in_hospital == "No") %>% select(Component_1) %>% pull(),
                                 temp %>% filter(abx_baby_in_hospital == "Yes") %>% select(Component_1) %>% pull())$p.value)
results = c(results, wilcox.test(temp %>% filter(abx_baby_in_hospital == "No") %>% select(Component_2) %>% pull(),
                                 temp %>% filter(abx_baby_in_hospital == "Yes") %>% select(Component_2) %>% pull())$p.value)
results = c(results, wilcox.test(temp %>% filter(abx_baby_in_hospital == "No") %>% select(Component_3) %>% pull(),
                                 temp %>% filter(abx_baby_in_hospital == "Yes") %>% select(Component_3) %>% pull())$p.value)

# Antibiotics for baby after hospital
temp = model[[1]] %>% left_join(sampleMetadata %>% select(subject, abx_baby_after_hospital) %>% unique())
results = c(results, wilcox.test(temp %>% filter(abx_baby_after_hospital == "No") %>% select(Component_1) %>% pull(),
                                 temp %>% filter(abx_baby_after_hospital == "Yes") %>% select(Component_1) %>% pull())$p.value)
results = c(results, wilcox.test(temp %>% filter(abx_baby_after_hospital == "No") %>% select(Component_2) %>% pull(),
                                 temp %>% filter(abx_baby_after_hospital == "Yes") %>% select(Component_2) %>% pull())$p.value)
results = c(results, wilcox.test(temp %>% filter(abx_baby_after_hospital == "No") %>% select(Component_3) %>% pull(),
                                 temp %>% filter(abx_baby_after_hospital == "Yes") %>% select(Component_3) %>% pull())$p.value)

# Bacteroides profile
temp = model[[1]] %>% left_join(sampleMetadata %>% select(subject, bacteroides_profile) %>% unique())
results = c(results, wilcox.test(temp %>% filter(bacteroides_profile == "low_Bacteroides") %>% select(Component_1) %>% pull(),
                                 temp %>% filter(bacteroides_profile == "normal_Bacteroides") %>% select(Component_1) %>% pull())$p.value)
results = c(results, wilcox.test(temp %>% filter(bacteroides_profile == "low_Bacteroides") %>% select(Component_2) %>% pull(),
                                 temp %>% filter(bacteroides_profile == "normal_Bacteroides") %>% select(Component_2) %>% pull())$p.value)
results = c(results, wilcox.test(temp %>% filter(bacteroides_profile == "low_Bacteroides") %>% select(Component_3) %>% pull(),
                                 temp %>% filter(bacteroides_profile == "normal_Bacteroides") %>% select(Component_3) %>% pull())$p.value)


resultsAdj = p.adjust(results, "BH")
resultsNoCorrection = matrix(results, nrow=3)
resultsCorrected = matrix(resultsAdj, nrow=3)
```

```{r 3d plots of loadings}
plot_ly(model[[1]], x=~Component_1, y=~Component_2, z=~Component_3, color=~birth_mode)
plot_ly(model[[1]] %>% left_join(sampleMetadata %>% select(subject, feeding_method)), x=~Component_1, y=~Component_2, z=~Component_3, color=~feeding_method)

plot_ly(model[[2]], x=~Component_1, y=~Component_2, z=~Component_3, color=~phylum)
```

```{r heatmap plot}
fullModelPlotHeatmap(model, 3, subjectNameCol = "subject", groupedVariable = "phylum", fullNameVariable = "motus", subjectList = model[[1]] %>% filter(Component_3 > 12) %>% select(subject) %>% pull())
```