---
title: "generateCountData"
author: "RvdP"
date: "2023-08-15"
output: html_document
---

```{r requirements}
library(tidyverse)
library(patchwork)
library(timeOmics)
library(tscount)
```

```{r functions}
simulate = function(mod, para, nIndiv, nTime, disper, nTaxa, nSc1, nSc2, nSc3, meta){
  # Comments: (brace yourselves)
  # model is useless, only contains one item
  # para can be changed to be separate parameters for the function: intercept, past_obs, xreg
  # tsglm.sim expects para as a list, but you can fix this differently
  
  TAXA = data.frame(matrix(ncol=nTaxa, nrow=nIndiv*nTime))
  colnames(TAXA) = paste0("Taxa_", 1:nTaxa)
  
  for(i in 1:nTaxa){
    if(i<=nSc1){#Time
      k=1
    }else if(i<=nSc1+nSc2){#Group
      k=2
    }else if(i<=nSc1+nSc2+nSc3){#Time+Group+Time*Group
      k=3
    }else {#No
      k=4
    }
    
    count = c()
    for(j in 1:nIndiv){
      t = c(tsglm.sim(n=nTime, param = para[[k]], model=model, 
                     xreg=matrix(c(1:nTime,
                                   rep(meta$Group[meta$Indiv==j][1],nTime),
                                   1:nTime*rep(meta$Group[meta$Indiv==j][1],nTime)),ncol=3), 
                     link="identity",
                     distr="nbinom", distrcoefs=c(size=1/disper))$ts)
      count<-c(count,t)
    }
    while(!any(count==0)){#At least one zero (Needed to run ZIGMM)
      count<-c()
      for(j in 1:nIndiv){
        t<-c(tsglm.sim(n=nTime, param = para[[k]], model=model, 
                       xreg=matrix(c(1:nTime,rep(meta$Group[meta$Indiv==j][1],nTime),
                                     1:nTime*rep(meta$Group[meta$Indiv==j][1],nTime)),ncol=3),
                       link="identity",
                       distr="nbinom", distrcoefs=c(size=1/disper))$ts)
        count<-c(count,t)
      } 
    }
    TAXA[,i]<-count
  }
  
  
  return(TAXA)
}


```

```{r run it}
model = list(past_obs = 1)
disp_1 = 0.1
param_1 = list(list(intercept=runif(1,0,5), past_obs=0.04,  xreg=c(1.5,0,0)),
                list(intercept=runif(1,0,5), past_obs=0.04,  xreg=c(0,13,0)),
                list(intercept=runif(1,0,5), past_obs=0.04,  xreg=c(1.5,13,5)),
                list(intercept=runif(1,0,5), past_obs=0.04,  xreg=c(0,0,0)))

nIndiv = 20
nTime = 10
metaDF = data.frame(Time=rep(c(1:nTime),nIndiv),
                   Indiv=rep(1:nIndiv,each=nTime),
                   Group=rep(0:1,each=nIndiv*nTime/2))

n_iter = 10 # Number of iterations of the loop
list_of_frames <- replicate(n_iter, data.frame())

for(i in 1:n_iter) {
  df_Scenario1 = simulate(model,param_1,nIndiv,nTime, disp_1, 300, 10,10,10,metaDF)
  list_of_frames[[i]] = df_Scenario1
}
```